<!DOCTYPE html>
<html lang="en" >
<head>
  <meta charset="UTF-8">
  <title></title>
  <link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css'>
<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css'>
<link rel="stylesheet" href="/home/cedcoss/git /events_phalcon/src/app/views/index/style.css">

</head>
<body>
<!-- partial:index.partial.html -->
 <nav class="navbar navbar-expand-lg navbar-light bg-light p-5 ">
  <h3 class="text-center"> check Weather of Your City</h3>
  <!--<a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="order">Checkout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/setting">Setting</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">checkout</a>
          <a class="dropdown-item" href="#"></a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="addpro">Add Product</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="role">Add Role</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="role/action">Action</a>
      </li>
    </ul>
   </div> -->
</nav>
<section class="section-products">
		<div class="container">
				<div class="row justify-content-center text-center">
						<div class="col-md-8 col-lg-6">
								<div class="header mt-5">
										<h3>Featured Product</h3>
										<h2>Popular Products</h2>
								</div>
                <nav class="navbar navbar-light bg-light">
                  <form class="form-inline" method="POST" action="">
                    <span>
                  <div class="row">
                    <input class="form-control mr-sm-2 col-sm" name="val" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0 col-sm m-5" name="submit" type="submit">Search</button>
                  </div>
                    <span>

                  </form>
                </nav>
               
						</div>
				</div>

        <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-md-8 col-lg-6 col-xl-4">
        <?php 
        // echo "<pre>";
        // print_r($book['current']);
        // foreach($book as $value) {
          # code...
          // print_r( $value,);

        // ?>
        <?php 
          // die;

        ?>
            <div class="card" style="color: #4B515D; border-radius: 35px;">
              <div class="card-body p-4">

                <div class="d-flex">
                  <h6 class="flex-grow-1"><?php echo $book['location']['name']; ?></h6>
                  <h6>15:07</h6>
                </div>

                <div class="d-flex flex-column text-center mt-5 mb-4">
                  <h6 class="display-4 mb-0 font-weight-bold" style="color: #1C2331;"><?php echo $book['current']['temp_c']; ?> </h6>
                  <span class="small" style="color: #868B94"><?php echo $book['current']['condition']['text']; ?></span>
                </div>

                <div class="d-flex align-items-center">
                  <div class="flex-grow-1" style="font-size: 1rem;">
                    <div><i class="fas fa-wind fa-fw" style="color: #868B94;"></i> <span class="ms-1"><?php echo $book['current']['last_updated']; ?>  </span></div>
                    <div><i class="fas fa-wind fa-fw" style="color: #868B94;"></i> <span class="ms-1"><?php echo $book['current']['wind_kph']; ?>km/hr  </span></div>
                    <div><i class="fas fa-tint fa-fw" style="color: #868B94;"></i> <span class="ms-1"><?php echo $book['current']['cloud']; ?></span></div>
                    <div><i class="fas fa-sun fa-fw" style="color: #868B94;"></i> <span class="ms-1"> 0.2h </span></div>
                  </div>
                  <div>
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-weather/ilu1.webp" width="100px">
                  </div>
                </div>

              </div>
            </div>

          </div>
        </div>
      <div class ="area mt-5">
        <?php
               foreach($area as $key => $value){
                //  echo $key;
                      // echo "<pre>";
                      // // print_r($area[$key]['name']);
                      // print_r($area);
                      // die;
              //  } 
              //  echo "<pre>";
              //       print_r($area['name']);
               ?>
            <div class="card mt-5 " style="width: 50rem ; margin-left:15%;background-color: #f2f2f2;">
                <div class="card-body ">
                  <h5 class="card-title  text-center"><?php echo $area[$key]['name'];  ?></h5><hr>
                  <h6 class="card-subtitle mb-2 text-muted "><?php echo $area[$key]['name'];  ?></h6>
                  <div class=" p-2">
                  <p class="card-text"><?php echo $area[$key]['url'];  ?> .</p>
                  <form method="POST" action="index/detail">
                    <input type="submit" class="btn btn-outline-success" name="area" value="<?php echo $area[$key]['name'];?>">
                  </form>
                  </div>
                </div>
            </div>
          <?php } ?>
               </div>

</div>
	<?php  ?>		
</section>
<!-- partial -->
  
</body>
</html>
